# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# Make vim the default editor
export EDITOR="vim"

# Don’t clear the screen after quitting a manual page
export MANPAGER="less -X"
# Highlight section titles in manual pages
# Less Colors for Man Pages
# http://linuxtidbits.wordpress.com/2009/03/23/less-colors-for-man-pages/
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;33;246m'   # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
# Make some commands not show up in history
export HISTORY_IGNORE="ls|ls *|cd|ll|la|cd -|pwd|exit|date|* --help"

# LESS options
#  -R Colors
#  -X Don't clear screen on quit
export LESS="-R -X"

# Disable oh-my-zsh updating of tmux window name
export DISABLE_AUTO_TITLE=true

# Homebrew and rbenv on path
export PATH="/usr/local/bin:$PATH:/usr/local/sbin"
export PATH="$HOME/.rbenv/bin:$PATH"
export MANPATH="/usr/local/man:/usr/local/mysql/man:/usr/local/git/man:$MANPATH"
export PATH="$HOME/bin:$PATH"

# Init rustup
[ -r $HOME/.cargo/env ] && source $HOME/.cargo/env

# Init rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# Init asdf
[ -r $HOME/.asdf/asdf.sh ] && source $HOME/.asdf/asdf.sh
