source ~/.antigen/antigen.zsh

#load the oh-my-zsh library
antigen-use oh-my-zsh

# Set the theme
# antigen-theme blinks # agnoster, juanghurtado
# . $HOME/.powerline/powerline/bindings/zsh/powerline.zsh
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

# Plugins
antigen-bundle github
antigen-bundle heroku
antigen-bundle osx
antigen-bundle pow
antigen-bundle rails
antigen-bundle rake
antigen-bundle bundler
antigen bundle zsh-users/zsh-syntax-highlighting

# Finished loading antigen
antigen-apply

# Custom
for file in ~/.zsh/{aliases,functions}.zsh; do
	[ -r $file ] && source $file
done
unset file

# Include secrets...
[ -r ~/.secret ] && source ~/.secret

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# For LaTeX stuff
eval `/usr/libexec/path_helper -s`

# gpg-agent
if [[ $(uname) == Darwin ]]; then
  if [ -f "${HOME}/.gpg-agent-info" ]; then
    . "${HOME}/.gpg-agent-info"
    export GPG_AGENT_INFO
    export SSH_AUTH_SOCK
  fi
fi

# RVM
[ -r ~/.rvm ] && export PATH="$PATH:$HOME/.rvm/bin"

cd ..;cd -
