source ~/.antigen.zsh

# load the oh-my-zsh library
antigen use oh-my-zsh


# Set the theme
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

antigen bundle github
antigen bundle heroku
antigen bundle osx
antigen bundle rails
antigen bundle rake
antigen bundle bundler
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle wd

# Finished loading antigen
antigen apply

# Custom
for file in ~/.zsh/{aliases,functions,completion}.zsh; do
	[ -r $file ] && source $file
done
unset file

# Include secrets...
[ -r ~/.secret ] && source ~/.secret
